alphagov/government-service-design-manual

- service-manual/technology/spending-controls.md
Does three things:
- removes whitespace in Markdown document
- fixes link for digital and technology section
- adds link to MPA organisation page on GOV.UK
> Whitespace removal, href fixes, add MPA link

- service-manual/start/index.md
But since GOV.UK should be a record of Government itself, we should still
reference him by pointing to his page on GOV.UK.
> Stephen Kelly is no longer COO

- service-manual/user-centred-design/resources/patterns/index.md
- service-manual/user-centred-design/resources/patterns/national-insurance-number.md
On the NINO pattern page: Changed link to wikipedia to a link to our
hackpad discussion of this pattern.
On the patterns index page: changed 'insurance' to 'Insurance' to align
with advice in pattern
(This is part of a programme to rationalise and improve our forms guidance)
> Add hackpad link to NINO pattern

- service-manual/user-centred-design/resources/patterns/index.md
Some design patterns are rather precise 'do it like this'; others are
more about how to think about a topic. This rearrangement groups them
according to the way they might be used.
> Change order of design patterns to show typical use

- Gemfile
- Gemfile.lock
We don't need Gemfury for any of the gems, so delete the requirement.
> Remove references to Gemfury

- _includes/layouts/_body.html
- service-manual/assets/javascript/analytics-init.js
All apps should use Universal alongside Classic so we can test the implementation and be ready to complete the upgrade to Universal once testing is complete.
* Update frontend toolkit to 3.3.0 to pull in the latest analytics javascript
* Add an `analytics-init` file to configure and start the tracker (reference: https://github.com/alphagov/govuk_frontend_toolkit/blob/master/docs/analytics.md#create-an-analytics-tracker)
* Remove inline script tags and `text/javascript` attributes
Because js files aren't concatenated and minified in the service manual I've avoided pulling in the print and error tracking for now.
Story: https://www.pivotaltracker.com/story/show/89525510
> Begin migration from Classic to Universal analytics

- service-manual/assisted-digital/index.md
Text added to Assisted Digital (AD) pages in the service manual to explain
newly added policy detail around who AD support needs to provided for, to
meet the service standard.
Opening PR as me. Content originally committed by @benaldo1975.
> Details of who AD support needs to be provided for

- service-manual/assisted-digital/index.md
Text added to explain newly-agreed policy reasons why departments may not
need to provide assisted digital support for a service's users.
Originally committed by @benaldo1975; PRing as me after fixing the commit message.
> Explain why AD is not always required

- Gemfile
- Gemfile.lock
- Rakefile
- _plugins/jekyll_rummageable/indexer.rb
- app.rb
Index documents using the "manual" formats
This depends on alphagov/rummager#399; I'll
deploy both that and this change together.
So that we can move to using the `unified_search` endpoint, we want to
index documents from the service manual the same as if they were from
one of the standard manuals on GOV.UK (ie, using the recently introduced
`manual` and `manual-section` formats).
This requires several changes:
- update version of rummageable, since the old one doesn't allow anything
except for a very limited set of fields to be sent.
- the documents from the manual need to be indexed with their type set
to `manual_section`.
- manuals are generally associated with an organisation, so associate
this manual with the GDS organisation.
- the titles in search of all existing `manual_section` …
> Index like other manuals

- Rakefile
- app.rb
Instead of using the old /search endpoint on rummager, use the
/unified_search endpoint, applying a filter on the manual field to
return only service-manual documents.
In my testing, this returns the same results as using the /search
endpoint, and they look the same.  The ordering may vary slightly,
because the unified_search endpoint applies some popularity adjustments
to its weighting, but I expect these to be an improvement, if anything.
Also, use Plek.find("rummager") instead of Plek.find("search") now that
we've defined a rummager name; we should start moving to that, instead
of search when we're making changes in that area.
Depends on https://github.com/alphagov/rummager/pull/402.
> Use the unified search endpoint

- _search/includes/layouts/_footer_support_links.liquid
- Research shows users think clicking the "Cymraeg" link will take
them to a translated version of the page they are on, rather than a
specific list of services GOV.UK has translated into Welsh. The
phrase "Rhestr o Wasanaethau Cymraeg" better describes the nature of
the page users are taken to.
- Originally changed this in https://github.com/alphagov/static/pull/578
and am now updating everything that contains our footer without
pulling in `static`.
("Rhestr o Wasanaethau Cymraeg" means "List of Welsh services", for those curious.)
> Change the text of the "Cymraeg" link in the footer

- service-manual/user-centred-design/browsers-and-devices.md
Big changes here include:
- Dropping IE 6 from the list of browsers, we are seeing ~0.06% usage
- Move IE 7 down to compliant, it has just dropped out of 95% in the
past month but it is a different enough rendering engine it should
still be looked at
- Drop Android 2.3, its usage is around 0.2%
- Drop Blackberry, its usage is 0.1%
- Move Windows Phone 8.1 into compliant as its usage is within our 95%
support level
> Update browser guidance based on latest numbers

- service-manual/assets/stylesheets/views/_standard.scss
- service-manual/digital-by-default-26-points/index.md
- service-manual/digital-by-default/assessments-at-gds.md
- service-manual/digital-by-default/index.md
The Digital by Default Service Standard has been revised to 18 points.
These changes:
- move the Digital by Default Service Standard with 26 points
- add new Digital Service Standard content with 18 points
- provide a link from the new Digital Service Standard to the older Digital by Default Service Standard in the introduction
- provide a link back from the 26 point Digital by Default Service Standard to the new updated 18 point Service Standard in a status notice
- change 26 points to 18 points in the assessment criteria
> New 18 point Digital Service Standard

- _includes/layouts/_body.html
- service-manual/assets/javascript/analytics-init.js
__To be deployed 2 June.__
Following on from https://github.com/alphagov/govuk_frontend_toolkit/pull/194
* Bump govuk_frontend_toolkit to pull in latest analytics
* Remove references to classic tracker
* Remove classic specific arguments (eg custom variable name and scope)
* Update references of `GOVUK.Tracker` to `GOVUK.Analytics`
> Remove Google Analytics classic

- service-manual/digital-by-default-26-points/index.md
The title for the Digital by Default Service Standard was the same for
both the new 18 point standard and the older 26 point standard "Digital by Default Service Standard", 
this was causing two hero boxes (large red boxes) to be displayed on each
index page. 
Making the title unique for the 26 point standard fixes this.
> Make title unique for 26 point Digital by Default Service Standard

- _includes/layouts/_footer_top.html
This link still goes to /visas-immigration which redirects 
to /browse/visas-immigration.
This breaks the In-Page Analytics view in Google Analytics,
because the next page tracked doesn't match the link.
Updated to go directly to /browse/visas-immigration.
> Update visa-immigration link

- service-manual/domain-names/email.md
- service-manual/operations/operating-servicegovuk-subdomains.md
SPF provides a public list of servers that you expect to be sending mail for
your domain. The recipient can check this list to determine whether the
server from which it has recieved mail is on the list and hence whether the
message is likely to be authentic. This method can be spoofed by careful editing
of the email Received-From header, so it is an indicator of authenticity, not
a guarantee.
DKIM (DomainKey Identified Mail) allows you to publish a public key in DNS and
to sign all your mail with your private key. The recipient can check that any
mail it receives are signed with that public key and hence can know that the
email it has received has been sent by the organisation in control of that
domain name. It is hard to forge unless you are in control of both the sending
server (and …
> Change wording about DKIM/SPF

- service-manual/assets/stylesheets/layouts/_gsdm.scss
Here #content is styling the HTML5 `<main>` element, which isn’t [block by
default](http://caniuse.com/#feat=html5semantic). 
Set it to be block to fix the layout in IE - where the layout
is currently the full-width of the page.
> Add display:block to #content to fix width in IE

- _includes/layouts/_footer_top.html
This adds the link to the new "Childcare and parenting" browse page in the footer.
See PR on static for previous art: https://github.com/alphagov/static/pull/622
> Add Childcare and parenting link in footer

- service-manual/operations/devops.md
- service-manual/operations/index.md
- service-manual/operations/service-management.md
DevOps is a portmanteau of 'development' and 'operations', and in some ways
is a good reflection of one of its core tenets. Since each word can be used
individually, we should style this correctly.
Colloboration amongs operations and development teams is central to DevOps,
so since neither party rules the roost all the time, we should capitalise
the start of each part of the portmanteau.
> Properly capitalise DevOps

- service-manual/assisted-digital/action-plan.md
- These were appearing as in-line asterisks rather than bullets
because it turns out that Markdown syntax requires a blank line
between introductory text and the * for bullets.
Thanks (embarrassingly) to @benaldo1975 for pointing this out.
> Correctly render bulleted lists

- service-manual/assisted-digital/action-plan.md
- For the last time. _Please_. The GitHub markdown view link obviously
failed when I couldn't find any asterisks in the preview of
https://github.com/alphagov/government-service-design-manual/pull/611,
'cause post-deploy today there were asterisks in this section instead of
bullet points. :goat:
> Really fix the displaying of bullet points in action_plan.md

- service-manual/making-software/development-environment.md
I'm seeing DS2 RFPs where the client copies and pastes this into the requirements for a development environment for alpha. 
Some of these 'required' requirements would prevent using some IaaS platforms that would be good for hosting an alpha, e.g. Heroku/AWS ECS.
Moved 'run own operating system' under desired, perhaps we could also make it clearer that containers are ok?
Relaxed root access requirement and dropped the minimum RAM requirements.
> Changes to Development environments

- service-manual/making-software/information-security.md
The Information Security section still contains references to CLAS consultants, Business Impact Levels and IS1 despite many of these having been withdrawn.
This is an attempt to at least remove the outdated content, if not to replace it yet with up to date content.
> Update infosec guidance to remove outdated concepts

- service-manual/user-centred-design/resources/patterns/start-pages.md
Based on further Hackpad discussion: https://designpatterns.hackpad.com/Start-pages-8fitVQYufJX
... tweaked the text to: (1) clarify that we'll usually create a start page for a new service, but only if it's the best way of meeting the user need; and (2) encourage service teams to get in touch with the content team sooner rather than later (in case we need some time to clarify the best way of joining up the service to GOV.UK).
What do you think, @timpaul ?
> Clarify - most (not all) services get start pages

- service-manual/user-centred-design/browsers-and-devices.md
This updates the browsers and devices page with the latest support information, and adds some explanatory text around compliant / functional (fixing https://github.com/alphagov/government-service-design-manual/issues/621).
> Update browsers and devices page

- _includes/layouts/_footer_support_links.html
- It was advised that we include this link prominently in the (rare)
event of legal action against us for something on the site.
- Related to https://github.com/alphagov/static/pull/714.
> Add a link to GOV.UK's Terms and Conditions to the footer

- service-manual/start/index.md
A video of a Francis Maude talk at SPRINT13 is no longer working. This
commit removes the video, and changes the text around it so it still
makes sense.
> Remove link to non-working video

- service-manual/start/index.md
In #633 we removed an old video of Francis Maude at SPRINT13 which had stopped working.
This video has now been restored, so we should also restore the video in the service manual. This is a better outcome than removing the video entirely.
This pull request reverts the commit that removed the video.
> Revert "Remove link to non-working video"

- _includes/_phases.html
- service-manual/phases/alpha.md
There are a couple of instances of the word users which should be users'
> Add missing apostrophes to 'users' where appropriate

- README.md
- service-manual/agile/features-of-agile.md
- service-manual/agile/index.md
- service-manual/agile/running-retrospectives.md
- service-manual/agile/what-agile-looks-like.md
- service-manual/agile/writing-user-stories.md
- service-manual/governance/governance-principles.md
- service-manual/governance/how-delivery-teams-manage-their-work.md
- service-manual/governance/seeing-progress.md
- service-manual/governance/setting-up-the-right-reporting.md
- service-manual/governance/what-to-expect-from-the-show-and-tell.md
- service-manual/the-team/working-environment.md
As we migrate sections away from the old service manual we need to stop indexing the old service manual in search.
Metadata can be added to each page or an array of patterns to exclude from search can be defined in config.yml.
This documents the metadata which we think for the moment is safer and easier to manage than the patterns in config.
The agile delivery section has already been migrated away from the old service manual to the new one. This adds the metadata to the related agile delivery pages.
> Exclude agile delivery from the search index

- service-manual/domain-names/email.md
- service-manual/operations/operating-servicegovuk-subdomains.md
CTS has recently published a blueprint for email configuration, including the use of DMARC which includes SPF and DKIM. We should be linking to that rather than have separate email server config guidance.
> Update email guidance to refer to CTS email blueprint

- service-manual/phases/beta.md
Change language in the beta guidance to refer to them as services, not prototypes.
Reasoning:
* They're not prototypes - they're production services.
* It confuses our language around what a prototype is. We want services to continue prototyping during beta, this is not the same as building a production service.
> Refer to beta services as services, not prototypes

- service-manual/governance/introduction-to-governance-for-service-delivery.md
- service-manual/governance/scaling-a-service-team.md
- service-manual/governance/when-to-scale-up.md
- service-manual/measurement/completion-rate.md
- service-manual/measurement/cost-per-transaction.md
- service-manual/measurement/digital-takeup.md
- service-manual/measurement/index.md
- service-manual/measurement/other-kpis.md
- service-manual/measurement/performance-platform.md
- service-manual/measurement/user-satisfaction.md
- service-manual/the-team/index.md
- service-manual/the-team/learning-and-development/foundation-day.md
- service-manual/the-team/learning-and-development/index.md
- service-manual/the-team/learning-and-development/service-manager-induction.md
- service-manual/the-team/recruitment/index.md
- service-manual/the-team/recruitment/performance-analyst-jd.md
- service-manual/the-team/working-with-specialists.md
- service-manual/user-centred-design/user-research/user-research-briefs.md
Periodically we remove pages from search that have been migrated to the new service manual so they do not appear in search twice.
> Remove from search content migrated prior to 2016-04-08

- service-manual/governance/funding-your-digital-service.md
The HM Treasury agile business case guidance was moved on GOV.UK, this fixes the URL to point to the updated guidance.
> Update link to agile business case guidance

- README.md
- docs/how-to-deploy.md
We're retiring that private wiki.
Original location: https://github.com/alphagov/wiki/wiki/HOWTO:-Deploy-the-Government-Service-Design-Manual
> Move deployment documentation from the private wiki

- service-manual/user-centred-design/resources/patterns/email-addresses.md
The "Find out more about email confirmation loops" link located [here]( 
https://www.gov.uk/service-manual/user-centred-design/resources/patterns/email-addresses.html#section-4) points to "#" instead of the Email confirmation loops page
> Fix email confirmation link

- service-manual/making-software/information-security.md
- service-manual/operations/penetration-testing.md
On 13/01/2016 the new CESG went live, looks like this broke these links
leaving them all (including the homepage) as 404s.
This commit updates them to what appears to be the best counterparts on
the new website.
> Map CESG URLs to new paths following website upgrade

- _includes/layouts/_inside_header.html
- _search/includes/layouts/_inside_header.liquid
This behaviour matches the new manual and thus tackles the fragmentation of search between the old and new manuals.
> Use the main gov.uk /search endpoint with filter_manual

- service-manual/digital-by-default/index.md
- service-manual/making-software/deployment.md
- service-manual/operations/hosting.md
- service-manual/phases/alpha.md
- service-manual/phases/beta.md
- service-manual/phases/discovery.md
- service-manual/phases/ideal-alphas.md
- service-manual/phases/live.md
- service-manual/phases/retirement.md
Periodically we remove pages from search that have been migrated to the new service manual so they do not appear in search twice.
This removes the following migrated urls:
- /service-manual/operations/hosting.html
- /service-manual/operations/hosting
- /service-manual/making-software/deployment.html
- /service-manual/making-software/deployment
- /service-manual/phases/retirement.html
- /service-manual/phases/retirement
- /service-manual/phases/live.html
- /service-manual/phases/live
- /service-manual/phases/beta.html
- /service-manual/phases/beta
- /service-manual/phases/ideal-alphas.html
- /service-manual/phases/alpha.html
- /service-manual/phases/alpha
- /service-manual/phases/ideal-alphas
- /service-manual/phases/discovery.html
- /service-manual/phases/discovery
- …
> Remove from search content migrated prior to 2016-08-15

- service-manual/governance/assurance-for-digital-services.md
Previous link to  "[Assurance](https://gds-governance-guidance.hackpad.com/Assurance-for-digital-services-mnH2GMxxMGD)" hackpad is no longer valid as this resource has been deleted
Proposing that this is replaced with a link to the "[Governance](https://gds-governance-guidance.hackpad.com/Introduction-to-governance-for-service-delivery-KvxJZEmVmdb)" hackpad. This is actually the one already referenced in the title of this link.
> Replacing broken hackpad link
