alphagov/government-service-design-manual

- service-manual/governance/funding-your-digital-service.md
Alex Holmes had some feedback on the accuracy of the content of this page, so we updated it based on his information to make it more accurate
> Governance — Funding a digital service updates

- service-manual/the-team/learning-and-development/service-manager-induction.md
I have had to change the request details as we are now fully booked for programmes until April 2015.
> Change of request details

- service-manual/user-centred-design/resources/patterns/alpha-beta.md
Add link to the alpha and beta banners Hackpad.
> Add missing link to Hackpad

- service-manual/the-team/learning-and-development/foundation-day.md
> Add new description and pre-learning

- service-manual/user-centred-design/resources/patterns/gender-and-sex.md
- service-manual/user-centred-design/resources/patterns/usernames.md
Following user-testing of this content, fix typos, broken links and clarity of guidance.
> Amends to design patterns

- _layouts/default-wrapper.html
- service-manual/assets/stylesheets/helpers/_user-satisfaction-survey.scss
Updated survey copy and link to reflect new survey
> Updated survey copy and link

- service-manual/the-team/learning-and-development/service-manager-induction.md
Updated service manager programme contact details
> Update service manager programme contact details

- service-manual/user-centred-design/resources/patterns/form-structure.md
Updated content that better reflects our current thinking about structuring forms for low-frequency use services.
> Update form structure pattern

- service-manual/user-centred-design/resources/patterns/dates.md
this is general advice, but occurs most often in this pattern
> Don't automatically tab between fields

- service-manual/assisted-digital/action-plan.md
> Fix bullet formatting

- service-manual/assisted-digital/action-plan.md
> Fixed link to exemplar services

- service-manual/the-team/learning-and-development/open-programme.md
> Update procurement session description

- service-manual/measurement/user-satisfaction.md
James Pallister in the content team took a look and suggested some changes.
And I somehow got the Feedback page guidance in here in a bodge merge.
> Update user satisfaction guidance following comments from content editor

- service-manual/domain-names/https.md
The team I work on is responsible for GOV.UK infrastructure, not GDS infrastructure.
> Update GDS Infrastructure Team to GOV.UK

- service-manual/identity-assurance/index.md
> Update GOV.UK Verify contact details

- service-manual/identity-assurance/index.md
For the upcoming launch of GOV.UK Verify we are updating the existing guidance on how to sign up for Verify to link to the official instructions.
> Link to Verify onboard process

- service-manual/operations/web-operations-stories.md
2 trailing spaces are deliberate. This is markdown `<br/>` behaviour.
See b9a718869347a526ab62e7cdee698a0850b17c89
> Fix formatting

- service-manual/user-centred-design/user-research/survey-design.md
This was requested by Katie Taylor.
> Remove example, which is an out-of-date survey 

- _layouts/default-wrapper.html
We have produced a new survey with better questions.
> Update the Surveymonkey link

- _layouts/default-wrapper.html
This mimics the recently updated copy on the new service manual. We hope it is more persuasive.
> Update banner copy to invite users to new survey

- service-manual/user-centred-design/user-research/survey-design.md
Looking at the design patterns work on gender, it might be better not to propose gender as a binary option choice.
> Change to gender question

- service-manual/user-centred-design/user-research/survey-design.md
> Disambiguate single response question
